### PR TITLE
Make compatible with both Xcode 7 and 8 and Swift 2.2/2.3.

### PR DESCRIPTION
**Pull request by designatednerd**
We'll point our CocoaPods at this fork until we're through the transition.

### CODE REVIEW

**Comment by designatednerd** [comment]
@mttrd @hkareem2222 @ebrenesc Code review please?

**Comment by mttrd** [comment]
LGTM

**Comment by designatednerd** [comment]
@hkareem2222 or @ebrenesc?

**Comment by ebrenesc** [comment]
LGTM

**Pull request merged**
